export enum OrderActionType {
  UPDATE_PAYEES = 'UPDATE_PAYEES',
  UPDATE_TITLE = 'UPDATE_TITLE',
  UPDATE_FEE = 'UPDATE_FEE',
  ADD_FEE = 'ADD_FEE',
  DELETE_FEE = 'DELETE_FEE',
  UPDATE_CART = 'UPDART_CART',
  ADD_CART = 'ADD_CART',
  DELETE_CART = 'DELETE_CART',
}
